# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Week2ScriptTool.py
# Created on: 2015-07-01 20:07:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.AddMessage("ArcPy has loaded")

arcpy.env.overwriteOutput = True

# Input variables:
Bus_Stops = arcpy.GetParameterAsText(0)
CensusBlocks2010 = arcpy.GetParameterAsText(1)

# Output variables
Bus_Stop_Select = Bus_Stops + "_Select"
Bus_Stop_Buffer = Bus_Stops + "_Buffer"
Bus_Stop_Intersect = Bus_Stops + "_Intersect"

where = arcpy.GetParameterAsText(2)
distance = str(arcpy.GetParameterAsText(3))
unit = "Feet"

spreadsheet = arcpy.GetParameterAsText(4)


arcpy.AddMessage("Beginning select")
# Process: Select
arcpy.Select_analysis(Bus_Stops,
                      Bus_Stop_Select,
                      where)
arcpy.AddMessage( "Select completed")

arcpy.AddMessage("Beginning buffer")
# Process: Buffer
arcpy.Buffer_analysis(Bus_Stop_Select,
                      Bus_Stop_Buffer,
                      distance + " " + unit,
                      "FULL", "ROUND", "NONE", "")
arcpy.AddMessage( "Buffer completed")

arcpy.AddMessage( "Beginning Intersect")

# Process: Intersect
arcpy.Intersect_analysis([CensusBlocks2010, Bus_Stop_Buffer],
                         Bus_Stop_Intersect, "ALL", "", "INPUT")

arcpy.AddMessage( "Intersect completed")



import csv
dataDictionary = {}

with arcpy.da.SearchCursor(Bus_Stop_Intersect, ["STOPID","POP10"]) as cursor:
    for row in cursor:
        busStopID = row[0]
        pop10 = row[1]
        if busStopID not in dataDictionary.keys():
            dataDictionary[busStopID] = [pop10]
        else:
            dataDictionary[busStopID].append(pop10)


with open(spreadsheet, 'wb') as csvfile:
    csvwriter = csv.writer(csvfile, delimiter=',')
    HEADERS = ['STOPID', 'Average Population']
    csvwriter.writerow(HEADERS)
    for busStopID in dataDictionary.keys():
        popList = dataDictionary[busStopID]
        averagePop = sum(popList)/len(popList)
        data = [busStopID, averagePop]
        csvwriter.writerow(data)

arcpy.AddMessage( "Data Analysis Complete")
