# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Week1Model.py
# Created on: 2016-08-29 22:53:54.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
CensusBlocks2010 = "C:\\Users\\William\\Desktop\\Python\\Week1\\Week1\\Working\\SanFrancisco.gdb\\SanFrancisco\\CensusBlocks2010"
Bus_Stops = "C:\\Users\\William\\Desktop\\Python\\Week1\\Week1\\Working\\SanFrancisco.gdb\\SanFrancisco\\Bus_Stops"
Bus_Stop_Select = "C:\\Users\\William\\Desktop\\Python\\Week1\\Week1\\Working\\SanFrancisco.gdb\\Week1Results\\Bus_Stop_Select"
Bus_Stops_Buffer = "C:\\Users\\William\\Desktop\\Python\\Week1\\Week1\\Working\\SanFrancisco.gdb\\Week1Results\\Bus_Stops_Buffer"
Bus_Stop_Intersect = "C:\\Users\\William\\Desktop\\Python\\Week1\\Week1\\Working\\SanFrancisco.gdb\\Week1Results\\Bus_Stop_Intersect"

# Process: Select
arcpy.Select_analysis(Bus_Stops, Bus_Stop_Select, "NAME = '71 IB' AND BUS_SIGNAG = 'Ferry Plaza'")

# Process: Buffer
arcpy.Buffer_analysis(Bus_Stop_Select, Bus_Stops_Buffer, "400 Feet", "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("C:\\Users\\William\\Desktop\\Python\\Week1\\Week1\\Working\\SanFrancisco.gdb\\SanFrancisco\\CensusBlocks2010 #;C:\\Users\\William\\Desktop\\Python\\Week1\\Week1\\Working\\SanFrancisco.gdb\\Week1Results\\Bus_Stops_Buffer #", Bus_Stop_Intersect, "ALL", "", "INPUT")

